alias g='git'
alias gst='g st'
alias gbr='g br'
alias gdiff='g diff'
alias gdc='g dc'
alias gci='g ci'
alias gco='g co'
alias glg='g lg'
alias glg2='g lg2'

alias docker-stop-all='docker stop $(docker ps -a -q)'
alias docker-rm-all='docker rm $(docker ps -a -q)'
